### ISSUE TITLE
My car info: Always 1 trip behind and data only availible after restart

### ISSUE THREAD

**Issue by CWfFO** [flobz/psa_car_controller#35]
Hello,
following situation:

**Describe the bug**
1. Server is started in following was to run in background 24h:
 _screen -mdS PSAServer python3 server.py -f test.json -c charge_config1.json -r -l 192.168.x.y -m xy@abc.de -P Secret_
Problem: I see only new trips if i restart the process. So kill -9 PID and then start it again with this command. And i don't see the last trip. Only the one before. 

**To Reproduce**
1. see above
2. occurs every time

**Config file**
{
    "client_id": "aaa",
    "client_secret": "bbb",
    "customer_id": "ccc",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2COpel",
    "refresh_token": "xxx",
    "remote_refresh_token": "yyy",
    "weather_api": null

**Environment (please complete the following information):**
 - OS: Raspbian buster
 - Android app Version myOpel 1.27.1

**Additional context**

KR
Christian

**Comment by jlayec** [comment]
Hello
- Improved trip engine available in hybrid branch of this repo. You can use it.
- Restart issue is solved in the branch of my forked repo. I will push it in this repo as soon as the last PR is merged.

**Comment by CWfFO** [comment]
Hi,
Thx. Do i need All files from your fork or Do i only need to change some files? 

BR

**Comment by CWfFO** [comment]
I am using now the hyprid branch of this repo. Still the last trip is missing and if i start in batch mode the country is not used from config. He is asking and a start in background is not possible.

**Comment by jlayec** [comment]
Hello,
- i rebuild a new branch here : https://github.com/jlayec/psa_car_controller/tree/update-slider-official or wait the #40 applied in this repo.
- the country is asked a single time to update the config file. Start 1st time without & and then you can use it.

**Comment by CWfFO** [comment]
Hi, 
i am using now https://github.com/jlayec/psa_car_controller/tree/update-slider-official
Still the same: I can see all trips in tab trips but slider don't show the time for the last trip. 
Problem with country is solved. My fault: I have overwritten all files and did not run the app decoder again.

**Comment by jlayec** [comment]
Hello
- well it depends what do you mean by 1 trip, the lengh of the trip and the frequency you hit get_vehicule_info. A minimum of 2-3 positions is needed (a trip of 10-15 minutes if frequency is every 5 minutes) to generate a new trip or a longer period of time.
- regarding the slider, I just retry today and I confirm that the slider is refreshed - but you need at least to reload the dashboard webpage or move anywhere the slider (to have the entire slider refreshed so you can select the last trip)

**Comment by CWfFO** [comment]
Hi, 
maybe best i give u an example:
Yesterday i used last time my car. So last trip in list: 15:57 CET 35,7 km 40 mins,. So enough points should be recorded. 
But slider stops at 03/07/21 14:00 h. To be honest: Not a big problem - only what i realized.
Other question: Is it possible to delete one specific record? Why ever i have a record with average speed of 874 km/h (would be really cool if this is true) and one with a consumtion of 57,5 kwh/100km. This entries are crashing the statistic on the summary page.

**Comment by jlayec** [comment]
Hello

I will need the debug of the trip engine.

Can you use my new branch https://github.com/jlayec/psa_car_controller/commits/feature-hybrid_compatibility or wait PR #43 merged in https://github.com/flobz/psa_car_controller/tree/feature-hybrid_compatibility

and then run DEBUGV debug level

`python3 server.py ___parameters_usually_used___ --debug DEBUGV`

**Comment by CWfFO** [comment]
Hi,
i used the first proposal. But something is not working. To the server i can not connect:
File "server.py", line 72, in <module>
    t1 = Thread(target=start_app, args=["My car info", args.base_path, args.debug < 20, args.listen, int(args.port)])
TypeError: '<' not supported between instances of 'str' and 'int'
Btw: is --debug DEBUGV correct? I used DEBUG.... 

KR

**Comment by jlayec** [comment]
Hello
I dont know why but the server.py file is not the correct one. You should have :
t1 = Thread(target=start_app, args=["My car info", args.base_path, **logger.level** < 20, args.listen, int(args.port)])
verify your checkout

**Comment by CWfFO** [comment]
And whats the correct command? --debug DEBUGV or DEBUG

KR

**Comment by jlayec** [comment]
Hello
The debug level should be DEBUGV
but the problem is not the command but the code you are executing. please resync from git depot.

**Comment by flobz** [comment]
I fixed "data only availible after restart" with 2fa4a896ddf32d39126335c1ea0fdfc25356c537.
@jlayec fix  "Always 1 trip behind" so I close the issue.

**Comment by CWfFO** [comment]
I have a similar problem now. New trips are only available after a restart...

**Comment by jlayec** [comment]
I didn't test the last version but there is still another optimization to be done : the update_trips function is triggered by DB insertion and executed before the DB commit so we always miss 1 position in the trip analysis. It should not be a critical issue but could be depending on the refresh timer configured.

**Comment by Flodu31** [comment]
Hi,
Same problem for me with the last version.
Florent

**Comment by flobz** [comment]
I change the way of updating trips after db insertion with b9fff4c.
 Can you give me feedback ?

**Comment by CWfFO** [comment]
It is working fine again 👍
